# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/boot" = {
      device = "/dev/disk/by-uuid/197F-34EF";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
    "/" = {
      device = "/dev/mapper/luks-01d69a9a-333d-4ed2-b9e5-26228bcf62ed";
      fsType = "ext4";
      # Evita escrituras innecesarias en la NAND del SSD al leer archivos
      options = [ "noatime" "nodiratime" ];
    };
  };

  boot.initrd.luks.devices = {
    # Raíz SSD: allowDiscards para TRIM + bypassWorkqueues para evitar cuellos de botella en CPU
    "luks-01d69a9a-333d-4ed2-b9e5-26228bcf62ed" = {
      device = "/dev/disk/by-uuid/01d69a9a-333d-4ed2-b9e5-26228bcf62ed";
      allowDiscards = true;
      bypassWorkqueues = true;
    };
    # Swap cifrada
    "luks-b54de5c2-237d-49ea-81d6-78bb5120d27f" = {
      device = "/dev/disk/by-uuid/b54de5c2-237d-49ea-81d6-78bb5120d27f";
      allowDiscards = true;
      bypassWorkqueues = true;
    };
  };

  swapDevices =
    [ { device = "/dev/mapper/luks-b54de5c2-237d-49ea-81d6-78bb5120d27f"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
